[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fermieopt"
version = "0.2.0"
description = "FermIE: Fernwärme-Investitions-und-Einsatzoptimierung. Ein Excel-basiertes Tool zur Optimierung von Fernwärme-Systemen, basierend auf 'flixOpt'."
authors = [
    { name = "Felix Bumann", email = "felixbumann387@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
keywords = ["optimization", "energy", "district heating", "fernwärme", "excel"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "flixOpt @git+https://github.com/flixOpt/flixOpt.git@v1.0.2",
    "pydantic >=2.10.1",
    "openpyxl >=-3.1.5",
]

[tool.setuptools.package-data]
fermieopt = ["flixOpt_excel/resources/ExcelTemplates/*.xlsx"]

[tool.ruff]
# Files or directories to exclude (e.g., virtual environments, cache, build artifacts)
exclude = [
    "venv",  # Virtual environments
    "build",  # Build artifacts
    "dist",  # Distribution files
    "__pycache__",  # Bytecode cache
    ".git",  # Git folder
    ".mypy_cache",  # MyPy cache
]

line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "N"]  # Enable linting rules by category (e.g., error, warnings, unused imports)
ignore = [  # Ignore specific rules
    "E501",  # Ignore line-length checks (use Black for formatting)
    "F401",  # Allow unused imports in some cases (use __all__)
    "N813",  # Allow importing of flixOpt as fx (lowercase)
    "N999",  # Ignore invalid module names
]
extend-fixable = ["B"]   # Enable fix for flake8-bugbear (`B`), on top of any rules specified by `fixable`.

# Apply rule exceptions to specific files or directories
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101"]  # Ignore assertions in test files

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
